apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-gateway
  labels:
    app: service-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-gateway
  template:
    metadata:
      labels:
        app: service-gateway
    spec:
      containers:
      - name: app-gateway
        image: jeanflores2c93/aforo255-nodejs-gateway:3
        ports:
        - name: http
          containerPort: 10000
        - name: envoy-admin
          containerPort: 9901