kind: Service
apiVersion: v1
metadata:
  name: app-service-gateway
spec:
  type: LoadBalancer
  selector:
    app: service-gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 10000
    name: http
